"""Public spectral mapping package."""

from __future__ import annotations

from .adapters.backends import _finalize_output_path, _remove_output_path, _temporary_output_path
from .adapters.sensors import (
    SensorBandDefinition,
    SensorSRFSchema,
    SensorSchemaError,
    _load_rsrf_sensor_schema,
    _simulate_segment_matrix,
    load_sensor_schemas,
)
from .build.library import (
    _load_siac_rows,
    build_mapping_library,
    prepare_mapping_library,
    validate_prepared_library,
)
from .engine.core import (
    CANONICAL_WAVELENGTHS,
    SUPPORTED_KNN_BACKENDS,
    SUPPORTED_NEIGHBOR_ESTIMATORS,
    SUPPORTED_OUTPUT_MODES,
    SUPPORTED_PERSISTED_KNN_INDEX_BACKENDS,
    SWIR_WAVELENGTHS,
    VNIR_WAVELENGTHS,
    BatchMappingArrayResult,
    BatchMappingResult,
    LinearSpectralMapper,
    MappingInputError,
    MappingResult,
    PreparedLibraryBuildError,
    PreparedLibraryCompatibilityError,
    PreparedLibraryManifest,
    PreparedLibraryValidationError,
    SpectralLibraryError,
    _assemble_full_spectrum,
    _assemble_full_spectrum_batch,
    _attach_sample_context,
    _default_sample_id,
    _ensure_supported_output_mode,
    _normalized_sample_ids,
    _normalized_source_sensors,
    _optional_float,
    _rustaccel,
)
from .engine.runtime import (
    SpectralMapper,
    _combine_neighbor_spectra_batch_accel,
    _finalize_target_sensor_batch_accel,
    _normalized_batch_rows,
    _refine_and_combine_neighbor_spectra_batch_accel,
    _segment_confidence_payload,
    _segment_confidence_payload_batch,
    _stitch_target_sensor_segment_rows,
    benchmark_mapping,
)

__all__ = [
    "CANONICAL_WAVELENGTHS",
    "SUPPORTED_KNN_BACKENDS",
    "SUPPORTED_NEIGHBOR_ESTIMATORS",
    "SUPPORTED_OUTPUT_MODES",
    "SUPPORTED_PERSISTED_KNN_INDEX_BACKENDS",
    "SWIR_WAVELENGTHS",
    "VNIR_WAVELENGTHS",
    "BatchMappingArrayResult",
    "BatchMappingResult",
    "LinearSpectralMapper",
    "MappingInputError",
    "MappingResult",
    "PreparedLibraryBuildError",
    "PreparedLibraryCompatibilityError",
    "PreparedLibraryManifest",
    "PreparedLibraryValidationError",
    "SensorBandDefinition",
    "SensorSRFSchema",
    "SensorSchemaError",
    "SpectralLibraryError",
    "SpectralMapper",
    "_assemble_full_spectrum",
    "_assemble_full_spectrum_batch",
    "_attach_sample_context",
    "_combine_neighbor_spectra_batch_accel",
    "_default_sample_id",
    "_ensure_supported_output_mode",
    "_finalize_output_path",
    "_finalize_target_sensor_batch_accel",
    "_load_rsrf_sensor_schema",
    "_load_siac_rows",
    "_normalized_batch_rows",
    "_normalized_sample_ids",
    "_normalized_source_sensors",
    "_optional_float",
    "_refine_and_combine_neighbor_spectra_batch_accel",
    "_remove_output_path",
    "_rustaccel",
    "_segment_confidence_payload",
    "_segment_confidence_payload_batch",
    "_simulate_segment_matrix",
    "_stitch_target_sensor_segment_rows",
    "_temporary_output_path",
    "benchmark_mapping",
    "build_mapping_library",
    "load_sensor_schemas",
    "prepare_mapping_library",
    "validate_prepared_library",
]
