from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen

import numpy as np
try:
    import matplotlib
    from openpyxl import load_workbook

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ModuleNotFoundError as exc:
    missing_name = exc.name or "an optional dependency"
    raise SystemExit(
        "scripts/build_official_mapping_examples.py requires the optional "
        f"internal-build dependencies (missing {missing_name}). Install them "
        'with `python3 -m pip install ".[internal-build]"`.'
    ) from exc


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from spectral_library import SpectralMapper


CANONICAL_WAVELENGTHS = np.arange(400, 2501, dtype=np.float64)
SEMANTIC_BANDS = ("ultra_blue", "blue", "green", "red", "nir", "swir1", "swir2")
COMPARABLE_PAIRWISE_BANDS = ("blue", "green", "red", "nir", "swir1", "swir2")
EXAMPLES_ROOT = REPO_ROOT / "examples" / "official_mapping"
SRF_ROOT = EXAMPLES_ROOT / "srfs"
QUERIES_ROOT = EXAMPLES_ROOT / "queries"
RESULTS_ROOT = EXAMPLES_ROOT / "results"
DOCS_ASSETS_ROOT = REPO_ROOT / "docs" / "assets"
OFFICIAL_SENSOR_DOC_PATH = REPO_ROOT / "docs" / "official_sensor_examples.md"
TMP_ROOT = REPO_ROOT / "tmp"
GENERATED_DOC_BANNER = "<!-- Generated by scripts/build_official_mapping_examples.py; do not edit by hand. -->"
EXAMPLE_K = 10
OVERLAY_TOP_NEIGHBORS = 5
FULL_LIBRARY_ENV_VAR = "SPECTRAL_LIBRARY_OFFICIAL_EXAMPLE_SIAC_ROOT"
DEFAULT_FULL_LIBRARY_ROOT = REPO_ROOT / "build" / "siac_spectral_library_real_full_raw_no_ghisacasia_no_understory_no_santa37"


@dataclass(frozen=True)
class BandSelection:
    band_id: str
    official_band: str
    segment: str
    source_key: str
    description: str


@dataclass(frozen=True)
class SensorSelection:
    sensor_id: str
    display_name: str
    short_label: str
    filename: str
    source_agency: str
    source_document: str
    source_url: str
    source_note: str
    bands: tuple[BandSelection, ...]


@dataclass(frozen=True)
class DownloadedArtifact:
    url: str
    sha256: str
    size_bytes: int
    downloaded_at_utc: str
    local_name: str
    etag: str | None = None
    last_modified: str | None = None

    def to_dict(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "url": self.url,
            "sha256": self.sha256,
            "size_bytes": self.size_bytes,
            "downloaded_at_utc": self.downloaded_at_utc,
            "local_name": self.local_name,
        }
        if self.etag:
            payload["etag"] = self.etag
        if self.last_modified:
            payload["last_modified"] = self.last_modified
        return payload


@dataclass(frozen=True)
class HeldOutTarget:
    sample_id: str
    source_id: str
    spectrum_id: str
    sample_name: str
    landcover_group: str
    title: str
    description: str

    @property
    def row_id(self) -> str:
        return f"{self.source_id}:{self.spectrum_id}:{self.sample_name}"


@dataclass(frozen=True)
class SelectedExampleRun:
    sample_id: str
    source_sensor: str
    target_sensor: str


OFFICIAL_SENSORS = (
    SensorSelection(
        sensor_id="modis_terra",
        display_name="Terra MODIS",
        short_label="MODIS Terra",
        filename="modis_terra.json",
        source_agency="NASA MCST",
        source_document="Terra_RSR_in-band.xlsx",
        source_url="https://mcst.gsfc.nasa.gov/sites/default/files/file_attachments/Terra_RSR_in-band.xlsx",
        source_note="Official Terra MODIS in-band relative spectral response workbook.",
        bands=(
            BandSelection("blue", "Band 3", "vnir", "band_3", "Blue"),
            BandSelection("green", "Band 4", "vnir", "band_4", "Green"),
            BandSelection("red", "Band 1", "vnir", "band_1", "Red"),
            BandSelection("nir", "Band 2", "vnir", "band_2", "Near infrared"),
            BandSelection("swir1", "Band 6", "swir", "band_6", "Shortwave infrared 1"),
            BandSelection("swir2", "Band 7", "swir", "band_7", "Shortwave infrared 2"),
        ),
    ),
    SensorSelection(
        sensor_id="sentinel2a_msi",
        display_name="Sentinel-2A MSI",
        short_label="Sentinel-2A",
        filename="sentinel2a_msi.json",
        source_agency="ESA Copernicus",
        source_document="COPE-GSEG-EOPG-TN-15-0007 - Sentinel-2 Spectral Response Functions 2024 - 4.0.xlsx",
        source_url="https://sentiwiki.copernicus.eu/__attachments/1692737/COPE-GSEG-EOPG-TN-15-0007%20-%20Sentinel-2%20Spectral%20Response%20Functions%202024%20-%204.0.xlsx",
        source_note="Official Sentinel-2 spectral response workbook; the examples use the S2A sheet.",
        bands=(
            BandSelection("ultra_blue", "B1", "vnir", "S2A_SR_AV_B1", "Coastal aerosol / ultra blue"),
            BandSelection("blue", "B2", "vnir", "S2A_SR_AV_B2", "Blue"),
            BandSelection("green", "B3", "vnir", "S2A_SR_AV_B3", "Green"),
            BandSelection("red", "B4", "vnir", "S2A_SR_AV_B4", "Red"),
            BandSelection("nir", "B8A", "vnir", "S2A_SR_AV_B8A", "Near infrared"),
            BandSelection("swir1", "B11", "swir", "S2A_SR_AV_B11", "Shortwave infrared 1"),
            BandSelection("swir2", "B12", "swir", "S2A_SR_AV_B12", "Shortwave infrared 2"),
        ),
    ),
    SensorSelection(
        sensor_id="landsat8_oli",
        display_name="Landsat 8 OLI",
        short_label="Landsat 8",
        filename="landsat8_oli.json",
        source_agency="USGS",
        source_document="Spectral Characteristics Viewer band JSON",
        source_url="https://landsat.usgs.gov/spectral-characteristics-viewer",
        source_note="Official USGS Spectral Characteristics Viewer JSON for Landsat 8 OLI/TIRS reflective bands 1-7.",
        bands=(
            BandSelection("ultra_blue", "Band 1", "vnir", "Landsat8OLITIRS1.json", "Coastal aerosol / ultra blue"),
            BandSelection("blue", "Band 2", "vnir", "Landsat8OLITIRS2.json", "Blue"),
            BandSelection("green", "Band 3", "vnir", "Landsat8OLITIRS3.json", "Green"),
            BandSelection("red", "Band 4", "vnir", "Landsat8OLITIRS4.json", "Red"),
            BandSelection("nir", "Band 5", "vnir", "Landsat8OLITIRS5.json", "Near infrared"),
            BandSelection("swir1", "Band 6", "swir", "Landsat8OLITIRS6.json", "Shortwave infrared 1"),
            BandSelection("swir2", "Band 7", "swir", "Landsat8OLITIRS7.json", "Shortwave infrared 2"),
        ),
    ),
    SensorSelection(
        sensor_id="landsat9_oli",
        display_name="Landsat 9 OLI",
        short_label="Landsat 9",
        filename="landsat9_oli.json",
        source_agency="USGS",
        source_document="Spectral Characteristics Viewer band JSON",
        source_url="https://landsat.usgs.gov/spectral-characteristics-viewer",
        source_note="Official USGS Spectral Characteristics Viewer JSON for Landsat 9 OLI/TIRS reflective bands 1-7.",
        bands=(
            BandSelection("ultra_blue", "Band 1", "vnir", "Landsat9OLITIRS1.json", "Coastal aerosol / ultra blue"),
            BandSelection("blue", "Band 2", "vnir", "Landsat9OLITIRS2.json", "Blue"),
            BandSelection("green", "Band 3", "vnir", "Landsat9OLITIRS3.json", "Green"),
            BandSelection("red", "Band 4", "vnir", "Landsat9OLITIRS4.json", "Red"),
            BandSelection("nir", "Band 5", "vnir", "Landsat9OLITIRS5.json", "Near infrared"),
            BandSelection("swir1", "Band 6", "swir", "Landsat9OLITIRS6.json", "Shortwave infrared 1"),
            BandSelection("swir2", "Band 7", "swir", "Landsat9OLITIRS7.json", "Shortwave infrared 2"),
        ),
    ),
)

SENSOR_BY_ID = {sensor.sensor_id: sensor for sensor in OFFICIAL_SENSORS}
PLOT_COLORS = {
    "modis_terra": "#0b5d8b",
    "sentinel2a_msi": "#e76f51",
    "landsat8_oli": "#2a9d8f",
    "landsat9_oli": "#6d597a",
}
PLOT_WINDOWS = {
    "ultra_blue": (410, 470),
    "blue": (430, 520),
    "green": (515, 595),
    "red": (620, 700),
    "nir": (810, 900),
    "swir1": (1540, 1685),
    "swir2": (2060, 2240),
}
HELD_OUT_TARGETS = (
    HeldOutTarget(
        sample_id="blue_spruce_needles",
        source_id="usgs_v7",
        spectrum_id="usgs_v7_002183",
        sample_name="Blue_Spruce DW92-5 needles    BECKa AREF",
        landcover_group="vegetation",
        title="Vegetation holdout",
        description="USGS v7 blue spruce needles spectrum used as a query while excluding only the matching prepared row id.",
    ),
    HeldOutTarget(
        sample_id="pale_brown_silty_loam",
        source_id="ecostress_v1",
        spectrum_id="ecostress_v1_002334",
        sample_name="Pale brown silty loam",
        landcover_group="soil",
        title="Soil holdout",
        description="ECOSTRESS pale brown silty loam spectrum used as a query while excluding only the matching prepared row id.",
    ),
    HeldOutTarget(
        sample_id="tap_water",
        source_id="ecostress_v1",
        spectrum_id="ecostress_v1_003451",
        sample_name="Tap water",
        landcover_group="water",
        title="Water holdout",
        description="ECOSTRESS tap water spectrum used as a query while excluding only the matching prepared row id.",
    ),
    HeldOutTarget(
        sample_id="asphalt_road",
        source_id="usgs_v7",
        spectrum_id="usgs_v7_000004",
        sample_name="Asphalt GDS376 Blck_Road old ASDFRa AREF",
        landcover_group="urban",
        title="Urban holdout",
        description="USGS v7 asphalt road spectrum used as a query while excluding only the matching prepared row id.",
    ),
)
HELD_OUT_TARGETS_BY_ID = {target.sample_id: target for target in HELD_OUT_TARGETS}
SENSOR_FILE_LABELS = {
    "modis_terra": "modis",
    "sentinel2a_msi": "sentinel2a",
    "landsat8_oli": "landsat8",
    "landsat9_oli": "landsat9",
}
SELECTED_TARGET_SENSOR_RUNS = (
    SelectedExampleRun("blue_spruce_needles", "modis_terra", "sentinel2a_msi"),
    SelectedExampleRun("pale_brown_silty_loam", "sentinel2a_msi", "landsat9_oli"),
    SelectedExampleRun("asphalt_road", "landsat8_oli", "modis_terra"),
)
FULL_SPECTRUM_SAMPLE_ID = "tap_water"
FULL_SPECTRUM_SOURCE_SENSOR = "sentinel2a_msi"
HOLDOUT_BATCH_SOURCE_SENSOR = "landsat8_oli"
HOLDOUT_BATCH_TARGET_SENSOR = "sentinel2a_msi"


def _single_query_path(sample_id: str, sensor_id: str) -> Path:
    return QUERIES_ROOT / "single" / f"{sample_id}_{sensor_id}.csv"


def _single_target_output_path(sample_id: str, source_sensor: str, target_sensor: str) -> Path:
    return RESULTS_ROOT / "selected" / (
        f"{sample_id}_{SENSOR_FILE_LABELS[source_sensor]}_to_{SENSOR_FILE_LABELS[target_sensor]}.csv"
    )


def _full_spectrum_output_path(sample_id: str, source_sensor: str) -> Path:
    return RESULTS_ROOT / "selected" / f"{sample_id}_{SENSOR_FILE_LABELS[source_sensor]}_full_spectrum.csv"


def _holdout_batch_query_path() -> Path:
    return QUERIES_ROOT / "batch" / f"{SENSOR_FILE_LABELS[HOLDOUT_BATCH_SOURCE_SENSOR]}_holdout_batch.csv"


def _holdout_batch_output_path() -> Path:
    return RESULTS_ROOT / "selected" / (
        f"{SENSOR_FILE_LABELS[HOLDOUT_BATCH_SOURCE_SENSOR]}_to_{SENSOR_FILE_LABELS[HOLDOUT_BATCH_TARGET_SENSOR]}_holdout_batch.csv"
    )


def _holdout_batch_diagnostics_path() -> Path:
    return RESULTS_ROOT / "selected" / (
        f"{SENSOR_FILE_LABELS[HOLDOUT_BATCH_SOURCE_SENSOR]}_to_{SENSOR_FILE_LABELS[HOLDOUT_BATCH_TARGET_SENSOR]}_holdout_batch_diagnostics.json"
    )


def _relative_repo_path(path: Path) -> str:
    resolved_path = path.resolve()
    try:
        return str(resolved_path.relative_to(REPO_ROOT.resolve()))
    except ValueError:
        return str(resolved_path)


def _shell_quote(value: str | Path) -> str:
    return shlex.quote(str(value))


def _resolve_full_library_root(explicit_root: Path | None = None) -> Path:
    candidates: list[Path] = []
    env_value = os.environ.get(FULL_LIBRARY_ENV_VAR, "").strip()
    if explicit_root is not None:
        candidates.append(explicit_root)
    elif env_value:
        candidates.append(Path(env_value))
    if DEFAULT_FULL_LIBRARY_ROOT not in candidates:
        candidates.append(DEFAULT_FULL_LIBRARY_ROOT)
    discovered = sorted(
        (path for path in (REPO_ROOT / "build").glob("siac_spectral_library_*") if path.is_dir()),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    candidates.extend(path for path in discovered if path not in candidates)

    for candidate in candidates:
        metadata_path = candidate / "tabular" / "siac_spectra_metadata.csv"
        spectra_path = candidate / "tabular" / "siac_normalized_spectra.csv"
        if metadata_path.exists() and spectra_path.exists():
            return candidate

    raise SystemExit(
        "Official example regeneration requires a composed full SIAC library. "
        f"Set {FULL_LIBRARY_ENV_VAR} or pass --siac-root to a build directory that contains "
        "tabular/siac_spectra_metadata.csv and tabular/siac_normalized_spectra.csv."
    )


def _inspect_full_library(
    siac_root: Path,
) -> tuple[int, dict[str, int], dict[str, dict[str, str]]]:
    metadata_path = siac_root / "tabular" / "siac_spectra_metadata.csv"
    targets_by_key = {
        (target.source_id, target.spectrum_id, target.sample_name): target
        for target in HELD_OUT_TARGETS
    }
    row_count = 0
    landcover_counts: Counter[str] = Counter()
    heldout_metadata: dict[str, dict[str, str]] = {}
    with metadata_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            row_count += 1
            landcover_counts[row.get("landcover_group") or "unlabeled"] += 1
            key = (row.get("source_id") or "", row.get("spectrum_id") or "", row.get("sample_name") or "")
            target = targets_by_key.get(key)
            if target is not None:
                heldout_metadata[target.sample_id] = dict(row)
    missing = sorted(target.sample_id for target in HELD_OUT_TARGETS if target.sample_id not in heldout_metadata)
    if missing:
        raise RuntimeError(f"Full SIAC library is missing configured held-out targets: {missing}")
    return row_count, dict(sorted(landcover_counts.items())), heldout_metadata


def _load_selected_spectra(
    siac_root: Path,
    row_keys_by_output_id: dict[str, tuple[str, str, str]],
) -> dict[str, np.ndarray]:
    spectra_path = siac_root / "tabular" / "siac_normalized_spectra.csv"
    wanted = dict(row_keys_by_output_id)
    nm_columns = [f"nm_{int(wavelength)}" for wavelength in CANONICAL_WAVELENGTHS]
    found: dict[str, np.ndarray] = {}
    with spectra_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            key = (row.get("source_id") or "", row.get("spectrum_id") or "", row.get("sample_name") or "")
            for output_id, expected in wanted.items():
                if key != expected:
                    continue
                raw_values = np.asarray(
                    [float(row[column]) if row[column] not in {"", None} else np.nan for column in nm_columns],
                    dtype=np.float64,
                )
                if np.isnan(raw_values).any():
                    valid = np.isfinite(raw_values)
                    if valid.sum() < 2:
                        raise RuntimeError(f"Insufficient valid points while loading {output_id}.")
                    spectrum = np.interp(CANONICAL_WAVELENGTHS, CANONICAL_WAVELENGTHS[valid], raw_values[valid])
                else:
                    spectrum = raw_values
                if spectrum.shape != CANONICAL_WAVELENGTHS.shape:
                    raise RuntimeError(f"Spectrum width mismatch while loading {output_id}.")
                found[output_id] = spectrum
                break
            if len(found) == len(wanted):
                break
    missing = sorted(output_id for output_id in wanted if output_id not in found)
    if missing:
        raise RuntimeError(f"Missing spectra for requested ids: {missing}")
    return found


def _load_neighbor_spectra(siac_root: Path, row_ids: set[str]) -> dict[str, np.ndarray]:
    row_keys_by_output_id: dict[str, tuple[str, str, str]] = {}
    for row_id in row_ids:
        source_id, spectrum_id, sample_name = row_id.split(":", 2)
        row_keys_by_output_id[row_id] = (source_id, spectrum_id, sample_name)
    return _load_selected_spectra(siac_root, row_keys_by_output_id)


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _download(url: str, destination: Path) -> DownloadedArtifact:
    destination.parent.mkdir(parents=True, exist_ok=True)
    downloaded_at_utc = datetime.now(timezone.utc).isoformat()
    with urlopen(url, timeout=60) as response:
        payload = response.read()
        etag = response.headers.get("ETag")
        last_modified = response.headers.get("Last-Modified")
    destination.write_bytes(payload)
    return DownloadedArtifact(
        url=url,
        sha256=_sha256_bytes(payload),
        size_bytes=len(payload),
        downloaded_at_utc=downloaded_at_utc,
        local_name=destination.name,
        etag=etag,
        last_modified=last_modified,
    )


def _download_json(url: str) -> tuple[list[dict[str, object]], DownloadedArtifact]:
    downloaded_at_utc = datetime.now(timezone.utc).isoformat()
    with urlopen(url, timeout=60) as response:
        payload_bytes = response.read()
        etag = response.headers.get("ETag")
        last_modified = response.headers.get("Last-Modified")
    payload = json.loads(payload_bytes.decode("utf-8"))
    artifact = DownloadedArtifact(
        url=url,
        sha256=_sha256_bytes(payload_bytes),
        size_bytes=len(payload_bytes),
        downloaded_at_utc=downloaded_at_utc,
        local_name=Path(url).name,
        etag=etag,
        last_modified=last_modified,
    )
    return payload, artifact


def _json_write(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def _weighted_center(wavelength_nm: np.ndarray, rsr: np.ndarray) -> float:
    return float(np.dot(wavelength_nm, rsr) / rsr.sum())


def _fwhm_nm(wavelength_nm: np.ndarray, rsr: np.ndarray) -> float:
    mask = rsr >= 0.5
    if not np.any(mask):
        return float(wavelength_nm[-1] - wavelength_nm[0])
    return float(wavelength_nm[mask][-1] - wavelength_nm[mask][0])


def _band_payload(band_id: str, segment: str, wavelengths_nm: np.ndarray, rsr: np.ndarray) -> dict[str, object]:
    support = rsr > 0
    return {
        "band_id": band_id,
        "segment": segment,
        "wavelength_nm": [round(float(value), 4) for value in wavelengths_nm.tolist()],
        "rsr": [round(float(value), 8) for value in rsr.tolist()],
        "center_nm": round(_weighted_center(wavelengths_nm, rsr), 4),
        "fwhm_nm": round(_fwhm_nm(wavelengths_nm, rsr), 4),
        "support_min_nm": round(float(wavelengths_nm[support][0]), 4),
        "support_max_nm": round(float(wavelengths_nm[support][-1]), 4),
    }


def _parse_modis_sensor(selection: SensorSelection, workbook_path: Path) -> dict[str, object]:
    workbook = load_workbook(workbook_path, read_only=True, data_only=True)
    bands: list[dict[str, object]] = []
    for band in selection.bands:
        worksheet = workbook[band.source_key]
        samples_by_wavelength: dict[float, list[float]] = {}
        for row in worksheet.iter_rows(min_row=2, values_only=True):
            if not row or row[2] is None or row[3] is None:
                continue
            wavelength = float(row[2])
            value = float(row[3])
            if value <= 0:
                continue
            samples_by_wavelength.setdefault(wavelength, []).append(value)
        wavelengths_nm = np.asarray(sorted(samples_by_wavelength), dtype=np.float64)
        rsr = np.asarray(
            [float(np.mean(samples_by_wavelength[wavelength])) for wavelength in wavelengths_nm],
            dtype=np.float64,
        )
        bands.append(_band_payload(band.band_id, band.segment, wavelengths_nm, rsr))
    return {"sensor_id": selection.sensor_id, "bands": bands}


def _parse_sentinel_sensor(selection: SensorSelection, workbook_path: Path) -> dict[str, object]:
    workbook = load_workbook(workbook_path, read_only=True, data_only=True)
    worksheet = workbook["Spectral Responses (S2A)"]
    rows = list(worksheet.iter_rows(values_only=True))
    header = [value if value is not None else "" for value in rows[0]]
    columns = {str(name): index for index, name in enumerate(header)}
    wavelength_index = columns["SR_WL"]
    bands: list[dict[str, object]] = []
    for band in selection.bands:
        response_index = columns[band.source_key]
        wavelengths: list[float] = []
        response: list[float] = []
        for row in rows[1:]:
            if row[wavelength_index] is None or row[response_index] is None:
                continue
            rsr = float(row[response_index])
            if rsr <= 0:
                continue
            wavelengths.append(float(row[wavelength_index]))
            response.append(rsr)
        bands.append(
            _band_payload(
                band.band_id,
                band.segment,
                np.asarray(wavelengths, dtype=np.float64),
                np.asarray(response, dtype=np.float64),
            )
        )
    return {"sensor_id": selection.sensor_id, "bands": bands}


def _parse_landsat_sensor(selection: SensorSelection) -> tuple[dict[str, object], list[dict[str, object]]]:
    base_url = "https://landsat.usgs.gov/landsat/spectral_viewer/c3-master/htdocs/data/bands"
    bands: list[dict[str, object]] = []
    artifacts: list[dict[str, object]] = []
    for band in selection.bands:
        payload, artifact = _download_json(f"{base_url}/{band.source_key}")
        wavelength_key, response_key = list(payload[0])
        wavelengths_nm = np.asarray([1000.0 * float(item[wavelength_key]) for item in payload], dtype=np.float64)
        rsr = np.asarray([float(item[response_key]) for item in payload], dtype=np.float64)
        positive = rsr > 0
        bands.append(_band_payload(band.band_id, band.segment, wavelengths_nm[positive], rsr[positive]))
        artifact_payload = artifact.to_dict()
        artifact_payload["official_band"] = band.official_band
        artifact_payload["band_id"] = band.band_id
        artifacts.append(artifact_payload)
    return {"sensor_id": selection.sensor_id, "bands": bands}, artifacts


def _simulate_sensor(sensor_schema: dict[str, object], spectrum: np.ndarray) -> dict[str, float]:
    values: dict[str, float] = {}
    for band in sensor_schema["bands"]:  # type: ignore[index]
        wavelengths = np.asarray(band["wavelength_nm"], dtype=np.float64)  # type: ignore[index]
        response = np.asarray(band["rsr"], dtype=np.float64)  # type: ignore[index]
        sampled = np.interp(wavelengths, CANONICAL_WAVELENGTHS, spectrum)
        values[str(band["band_id"])] = float(np.dot(sampled, response) / response.sum())
    return values


def _write_single_query(path: Path, reflectance: dict[str, float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["band_id", "reflectance"], lineterminator="\n")
        writer.writeheader()
        for band_id, value in reflectance.items():
            writer.writerow({"band_id": band_id, "reflectance": round(float(value), 8)})


def _write_batch_query(
    path: Path,
    sample_rows: dict[str, dict[str, float]],
    band_ids: tuple[str, ...],
    *,
    exclude_row_ids: dict[str, str] | None = None,
) -> None:
    include_exclude_row_id = bool(exclude_row_ids)
    fieldnames = ["sample_id"]
    if include_exclude_row_id:
        fieldnames.append("exclude_row_id")
    fieldnames.extend(band_ids)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for sample_id, values in sample_rows.items():
            row = {"sample_id": sample_id}
            if include_exclude_row_id:
                row["exclude_row_id"] = (exclude_row_ids or {}).get(sample_id, "")
            row.update({band_id: round(float(values[band_id]), 8) for band_id in band_ids})
            writer.writerow(row)


def _python_env() -> dict[str, str]:
    env = dict(os.environ)
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = str(SRC_ROOT) if not existing else str(SRC_ROOT) + os.pathsep + existing
    return env


def _run_cli(*args: str) -> str:
    command = [sys.executable, "-m", "spectral_library.cli", *args]
    completed = subprocess.run(
        command,
        check=False,
        cwd=REPO_ROOT,
        env=_python_env(),
        text=True,
        capture_output=True,
    )
    if completed.returncode != 0:
        if completed.stdout:
            print(completed.stdout, file=sys.stdout)
        if completed.stderr:
            print(completed.stderr, file=sys.stderr)
        raise subprocess.CalledProcessError(completed.returncode, command, output=completed.stdout, stderr=completed.stderr)
    return completed.stdout


def _metric_values(mapped: dict[str, float], truth: dict[str, float], band_ids: tuple[str, ...]) -> np.ndarray:
    missing = [band_id for band_id in band_ids if band_id not in mapped or band_id not in truth]
    if missing:
        raise RuntimeError(f"Missing metric bands {missing} while computing pairwise example metrics.")
    return np.asarray([mapped[band_id] - truth[band_id] for band_id in band_ids], dtype=np.float64)


def _prepare_example_runtime(prepared_root: Path, siac_root: Path) -> None:
    if prepared_root.exists():
        shutil.rmtree(prepared_root)
    _run_cli(
        "prepare-mapping-library",
        "--siac-root",
        str(siac_root),
        "--srf-root",
        str(SRF_ROOT),
        "--source-sensor",
        "modis_terra",
        "--source-sensor",
        "sentinel2a_msi",
        "--source-sensor",
        "landsat8_oli",
        "--source-sensor",
        "landsat9_oli",
        "--output-root",
        str(prepared_root),
    )


def _write_truth_tables(truth_spectra: dict[str, np.ndarray], sensors: dict[str, dict[str, object]]) -> None:
    truth_root = RESULTS_ROOT / "truth"
    truth_root.mkdir(parents=True, exist_ok=True)
    for sensor_id, schema in sensors.items():
        band_ids = tuple(str(band["band_id"]) for band in schema["bands"])  # type: ignore[index]
        path = truth_root / f"{sensor_id}_truth.csv"
        with path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=["sample_id", *band_ids], lineterminator="\n")
            writer.writeheader()
            for sample_id, spectrum in truth_spectra.items():
                row = {"sample_id": sample_id}
                row.update(
                    {
                        band_id: round(float(value), 8)
                        for band_id, value in _simulate_sensor(schema, spectrum).items()
                    }
                )
                writer.writerow(row)


def _collect_reflectance_rows(truth_spectra: dict[str, np.ndarray], sensors: dict[str, dict[str, object]]) -> dict[str, dict[str, dict[str, float]]]:
    by_sensor: dict[str, dict[str, dict[str, float]]] = {}
    for sensor_id, schema in sensors.items():
        sensor_rows: dict[str, dict[str, float]] = {}
        for sample_id, spectrum in truth_spectra.items():
            sensor_rows[sample_id] = _simulate_sensor(schema, spectrum)
        by_sensor[sensor_id] = sensor_rows
    return by_sensor


def _load_result_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _mean_abs_error(mapped: dict[str, float], truth: dict[str, float], band_ids: tuple[str, ...]) -> float:
    residuals = _metric_values(mapped, truth, band_ids)
    return float(np.mean(np.abs(residuals)))


def _rmse(mapped: dict[str, float], truth: dict[str, float], band_ids: tuple[str, ...]) -> float:
    residuals = _metric_values(mapped, truth, band_ids)
    return float(np.sqrt(np.mean(residuals**2)))


def _write_selected_cli_outputs(prepared_root: Path) -> None:
    selected_root = RESULTS_ROOT / "selected"
    selected_root.mkdir(parents=True, exist_ok=True)

    for example in SELECTED_TARGET_SENSOR_RUNS:
        target = HELD_OUT_TARGETS_BY_ID[example.sample_id]
        _run_cli(
            "map-reflectance",
            "--prepared-root",
            str(prepared_root),
            "--source-sensor",
            example.source_sensor,
            "--target-sensor",
            example.target_sensor,
            "--input",
            str(_single_query_path(example.sample_id, example.source_sensor)),
            "--output-mode",
            "target_sensor",
            "--exclude-row-id",
            target.row_id,
            "--output",
            str(_single_target_output_path(example.sample_id, example.source_sensor, example.target_sensor)),
        )
    _run_cli(
        "map-reflectance",
        "--prepared-root",
        str(prepared_root),
        "--source-sensor",
        FULL_SPECTRUM_SOURCE_SENSOR,
        "--input",
        str(_single_query_path(FULL_SPECTRUM_SAMPLE_ID, FULL_SPECTRUM_SOURCE_SENSOR)),
        "--output-mode",
        "full_spectrum",
        "--exclude-row-id",
        HELD_OUT_TARGETS_BY_ID[FULL_SPECTRUM_SAMPLE_ID].row_id,
        "--output",
        str(_full_spectrum_output_path(FULL_SPECTRUM_SAMPLE_ID, FULL_SPECTRUM_SOURCE_SENSOR)),
    )
    _run_cli(
        "map-reflectance-batch",
        "--prepared-root",
        str(prepared_root),
        "--source-sensor",
        HOLDOUT_BATCH_SOURCE_SENSOR,
        "--target-sensor",
        HOLDOUT_BATCH_TARGET_SENSOR,
        "--input",
        str(_holdout_batch_query_path()),
        "--output-mode",
        "target_sensor",
        "--output",
        str(_holdout_batch_output_path()),
        "--diagnostics-output",
        str(_holdout_batch_diagnostics_path()),
    )


def _write_pairwise_metrics(
    prepared_root: Path,
    truth_rows_by_sensor: dict[str, dict[str, dict[str, float]]],
) -> dict[tuple[str, str], dict[str, float]]:
    metrics_root = RESULTS_ROOT / "metrics"
    metrics_root.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, object]] = []
    metrics: dict[tuple[str, str], dict[str, float]] = {}

    mapper = SpectralMapper(prepared_root)

    for source_sensor in SENSOR_BY_ID:
        for target_sensor in SENSOR_BY_ID:
            if source_sensor == target_sensor:
                continue
            sample_mae: list[float] = []
            sample_rmse: list[float] = []
            for sample_id, reflectance in truth_rows_by_sensor[source_sensor].items():
                target = HELD_OUT_TARGETS_BY_ID[sample_id]
                mapping_result = mapper._map_reflectance_internal(
                    source_sensor=source_sensor,
                    reflectance=reflectance,
                    valid_mask=None,
                    output_mode="target_sensor",
                    target_sensor=target_sensor,
                    k=EXAMPLE_K,
                    min_valid_bands=1,
                    candidate_row_indices=mapper.candidate_row_indices(exclude_row_ids=[target.row_id]),
                )
                if mapping_result.target_reflectance is None:
                    raise RuntimeError(
                        f"Missing target_reflectance for {source_sensor} -> {target_sensor} sample {sample_id}."
                    )
                mapped = {
                    band_id: float(value)
                    for band_id, value in zip(mapping_result.target_band_ids, mapping_result.target_reflectance)
                }
                truth = truth_rows_by_sensor[target_sensor][sample_id]
                sample_mae.append(_mean_abs_error(mapped, truth, COMPARABLE_PAIRWISE_BANDS))
                sample_rmse.append(_rmse(mapped, truth, COMPARABLE_PAIRWISE_BANDS))

            payload = {
                "mean_abs_error": float(np.mean(sample_mae)),
                "rmse": float(np.mean(sample_rmse)),
                "sample_count": len(sample_mae),
                "evaluated_band_ids": list(COMPARABLE_PAIRWISE_BANDS),
                "evaluated_band_count": len(COMPARABLE_PAIRWISE_BANDS),
            }
            metrics[(source_sensor, target_sensor)] = payload
            rows.append(
                {
                    "source_sensor": source_sensor,
                    "target_sensor": target_sensor,
                    "source_label": SENSOR_BY_ID[source_sensor].short_label,
                    "target_label": SENSOR_BY_ID[target_sensor].short_label,
                    "evaluated_band_ids": "|".join(COMPARABLE_PAIRWISE_BANDS),
                    "evaluated_band_count": len(COMPARABLE_PAIRWISE_BANDS),
                    "mean_abs_error": payload["mean_abs_error"],
                    "rmse": payload["rmse"],
                    "sample_count": payload["sample_count"],
                }
            )

    csv_path = metrics_root / "pairwise_band_metrics.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "source_sensor",
                "target_sensor",
                "source_label",
                "target_label",
                "evaluated_band_ids",
                "evaluated_band_count",
                "mean_abs_error",
                "rmse",
                "sample_count",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)

    json_rows = [
        {
            **row,
            "evaluated_band_ids": list(COMPARABLE_PAIRWISE_BANDS),
        }
        for row in rows
    ]
    _json_write(
        metrics_root / "pairwise_band_metrics.json",
        {
            "comparison_band_ids": list(COMPARABLE_PAIRWISE_BANDS),
            "pairs": json_rows,
        },
    )
    return metrics


def _plot_selected_bands(sensor_payloads: dict[str, dict[str, object]]) -> None:
    DOCS_ASSETS_ROOT.mkdir(parents=True, exist_ok=True)
    figure, axes = plt.subplots(4, 2, figsize=(14, 11), constrained_layout=True)
    blank_axis = axes.flatten()[-1]
    axes_by_band = {
        band_id: axes.flatten()[index]
        for index, band_id in enumerate(SEMANTIC_BANDS)
    }
    blank_axis.axis("off")

    for band_id, axis in axes_by_band.items():
        x_min, x_max = PLOT_WINDOWS[band_id]
        axis.set_title(band_id.replace("_", " ").title())
        axis.set_xlim(x_min, x_max)
        axis.set_ylim(0, 1.05)
        axis.set_xlabel("Wavelength (nm)")
        axis.set_ylabel("Relative response")
        axis.grid(alpha=0.25)
        has_any = False
        for sensor in OFFICIAL_SENSORS:
            payload = sensor_payloads[sensor.sensor_id]
            matching = [
                band
                for band in payload["bands"]  # type: ignore[index]
                if str(band["band_id"]) == band_id
            ]
            if not matching:
                continue
            has_any = True
            band = matching[0]
            axis.plot(
                np.asarray(band["wavelength_nm"], dtype=np.float64),
                np.asarray(band["rsr"], dtype=np.float64),
                label=sensor.short_label,
                linewidth=2.0,
                color=PLOT_COLORS[sensor.sensor_id],
            )
        if not has_any:
            axis.text(0.5, 0.5, "Not available", transform=axis.transAxes, ha="center", va="center")

    handles, labels = axes_by_band["blue"].get_legend_handles_labels()
    blank_axis.text(
        0.5,
        0.72,
        "Official selected band responses\nused by the example runtime",
        ha="center",
        va="center",
        fontsize=15,
    )
    blank_axis.legend(handles, labels, loc="center", ncol=1, frameon=False)
    figure.savefig(DOCS_ASSETS_ROOT / "official_sensor_selected_bands.png", dpi=180)
    plt.close(figure)


def _plot_pairwise_heatmap(metrics: dict[tuple[str, str], dict[str, float]]) -> None:
    order = [sensor.sensor_id for sensor in OFFICIAL_SENSORS]
    matrix = np.full((len(order), len(order)), np.nan, dtype=np.float64)
    for row_index, source_sensor in enumerate(order):
        for column_index, target_sensor in enumerate(order):
            if source_sensor == target_sensor:
                continue
            matrix[row_index, column_index] = metrics[(source_sensor, target_sensor)]["mean_abs_error"]

    figure, axis = plt.subplots(figsize=(7.5, 6))
    image = axis.imshow(matrix, cmap="YlOrRd")
    axis.set_xticks(range(len(order)), [SENSOR_BY_ID[sensor_id].short_label for sensor_id in order], rotation=20, ha="right")
    axis.set_yticks(range(len(order)), [SENSOR_BY_ID[sensor_id].short_label for sensor_id in order])
    axis.set_title("Mean absolute error on four held-out class targets and the common six-band subset")
    for row_index in range(len(order)):
        for column_index in range(len(order)):
            if np.isnan(matrix[row_index, column_index]):
                axis.text(column_index, row_index, "-", ha="center", va="center", color="#555555")
            else:
                axis.text(
                    column_index,
                    row_index,
                    f"{matrix[row_index, column_index]:.4f}",
                    ha="center",
                    va="center",
                    color="#111111",
                )
    colorbar = figure.colorbar(image, ax=axis, shrink=0.86)
    colorbar.set_label("Mean absolute error (reflectance)")
    figure.tight_layout()
    figure.savefig(DOCS_ASSETS_ROOT / "official_pairwise_band_mae.png", dpi=180)
    plt.close(figure)


def _plot_holdout_batch_examples(
    sensor_payloads: dict[str, dict[str, object]],
    truth_rows_by_sensor: dict[str, dict[str, dict[str, float]]],
) -> None:
    rows = _load_result_rows(_holdout_batch_output_path())
    mapped_by_sample = {
        row["sample_id"]: {
            band_id: float(value)
            for band_id, value in row.items()
            if band_id != "sample_id" and value not in (None, "")
        }
        for row in rows
    }
    band_ids = [band["band_id"] for band in sensor_payloads[HOLDOUT_BATCH_TARGET_SENSOR]["bands"]]  # type: ignore[index]

    figure, axes = plt.subplots(2, 2, figsize=(13, 8), constrained_layout=True)
    x = np.arange(len(band_ids))
    width = 0.38

    for axis, target in zip(axes.flatten(), HELD_OUT_TARGETS):
        truth = truth_rows_by_sensor[HOLDOUT_BATCH_TARGET_SENSOR][target.sample_id]
        mapped = mapped_by_sample[target.sample_id]
        axis.bar(x - width / 2, [truth[band_id] for band_id in band_ids], width=width, label="Truth", color="#2a9d8f")
        axis.bar(
            x + width / 2,
            [mapped[band_id] for band_id in band_ids],
            width=width,
            label=f"Mapped from {SENSOR_BY_ID[HOLDOUT_BATCH_SOURCE_SENSOR].short_label}",
            color="#e76f51",
        )
        axis.set_xticks(x, [band_id.replace("_", "\n") for band_id in band_ids])
        axis.set_ylim(0, 0.85)
        axis.set_title(f"{target.title}: `{target.sample_id}`")
        axis.grid(axis="y", alpha=0.25)

    axes[0, 0].set_ylabel("Reflectance")
    axes[1, 0].set_ylabel("Reflectance")
    handles, labels = axes[0, 0].get_legend_handles_labels()
    figure.legend(handles, labels, loc="upper center", ncol=2, frameon=False, bbox_to_anchor=(0.5, 1.02))
    figure.savefig(DOCS_ASSETS_ROOT / "official_holdout_batch_examples.png", dpi=180)
    plt.close(figure)


def _load_batch_diagnostics_payload() -> dict[str, object]:
    return json.loads(_holdout_batch_diagnostics_path().read_text(encoding="utf-8"))


def _top_neighbor_row_ids(diagnostics_payload: dict[str, object]) -> set[str]:
    row_ids: set[str] = set()
    for result in diagnostics_payload["results"]:  # type: ignore[index]
        segments = result["diagnostics"]["segments"]  # type: ignore[index]
        for segment_name in ("vnir", "swir"):
            segment_payload = segments[segment_name]  # type: ignore[index]
            for row_id in segment_payload["neighbor_ids"][:OVERLAY_TOP_NEIGHBORS]:  # type: ignore[index]
                row_ids.add(str(row_id))
    return row_ids


def _plot_holdout_neighbor_overlays(
    holdout_spectra: dict[str, np.ndarray],
    neighbor_spectra: dict[str, np.ndarray],
    sensor_payloads: dict[str, dict[str, object]],
    truth_rows_by_sensor: dict[str, dict[str, dict[str, float]]],
) -> None:
    diagnostics_payload = _load_batch_diagnostics_payload()
    results_by_sample = {
        str(result["sample_id"]): result
        for result in diagnostics_payload["results"]  # type: ignore[index]
    }
    source_bands = sensor_payloads[HOLDOUT_BATCH_SOURCE_SENSOR]["bands"]  # type: ignore[index]
    band_by_id = {str(band["band_id"]): band for band in source_bands}
    figure, axes = plt.subplots(
        len(HELD_OUT_TARGETS),
        2,
        figsize=(16, 14),
        constrained_layout=True,
    )
    neighbor_colors = ("#355070", "#6d597a", "#2a9d8f", "#e9c46a", "#e76f51")
    segment_ranges = {
        "vnir": (400, 1000),
        "swir": (800, 2500),
    }
    segment_labels = {
        "vnir": "Visible to NIR retrieval",
        "swir": "NIR to SWIR retrieval",
    }

    for row_axes, target in zip(np.atleast_2d(axes), HELD_OUT_TARGETS):
        query_spectrum = holdout_spectra[target.sample_id]
        query_inputs = truth_rows_by_sensor[HOLDOUT_BATCH_SOURCE_SENSOR][target.sample_id]
        diagnostics_result = results_by_sample[target.sample_id]
        segment_payloads = diagnostics_result["diagnostics"]["segments"]  # type: ignore[index]

        for axis, segment in zip(row_axes, ("vnir", "swir")):
            segment_payload = segment_payloads[segment]  # type: ignore[index]
            query_band_ids = [str(value) for value in segment_payload["query_band_ids"]]  # type: ignore[index]
            band_centers = [float(band_by_id[band_id]["center_nm"]) for band_id in query_band_ids]
            band_values = [query_inputs[band_id] for band_id in query_band_ids]
            neighbor_ids = [str(value) for value in segment_payload["neighbor_ids"]]  # type: ignore[index]
            neighbor_distances = [float(value) for value in segment_payload["neighbor_distances"]]  # type: ignore[index]
            top_neighbors = list(zip(neighbor_ids, neighbor_distances))[:OVERLAY_TOP_NEIGHBORS]
            start_nm, end_nm = segment_ranges[segment]
            wavelength_mask = (CANONICAL_WAVELENGTHS >= start_nm) & (CANONICAL_WAVELENGTHS <= end_nm)

            axis.plot(
                CANONICAL_WAVELENGTHS[wavelength_mask],
                query_spectrum[wavelength_mask],
                color="#111111",
                linewidth=2.2,
                label="Held-out query spectrum",
            )
            axis.scatter(
                band_centers,
                band_values,
                color="#111111",
                s=20,
                zorder=5,
                label=f"{SENSOR_BY_ID[HOLDOUT_BATCH_SOURCE_SENSOR].short_label} query inputs",
            )

            for rank, (neighbor_id, distance) in enumerate(top_neighbors, start=1):
                neighbor_spectrum = neighbor_spectra[neighbor_id]
                color = neighbor_colors[(rank - 1) % len(neighbor_colors)]
                axis.plot(
                    CANONICAL_WAVELENGTHS[wavelength_mask],
                    neighbor_spectrum[wavelength_mask],
                    color=color,
                    linewidth=1.2,
                    alpha=0.9,
                    label=f"#{rank} {neighbor_id.split(':', 2)[-1]} ({distance:.3f})",
                )
                axis.scatter(
                    band_centers,
                    [_simulate_sensor(sensor_payloads[HOLDOUT_BATCH_SOURCE_SENSOR], neighbor_spectrum)[band_id] for band_id in query_band_ids],
                    color=color,
                    s=16,
                    zorder=4,
                )

            axis.set_xlim(start_nm, end_nm)
            axis.set_ylim(0, 0.85)
            axis.set_title(f"{target.title}: `{target.sample_id}` · {segment_labels[segment]}")
            axis.grid(alpha=0.22)
            axis.legend(loc="upper right", fontsize=7, frameon=False)

        row_axes[0].set_ylabel("Reflectance")

    axes[-1, 0].set_xlabel("Wavelength (nm)")
    axes[-1, 1].set_xlabel("Wavelength (nm)")
    figure.savefig(DOCS_ASSETS_ROOT / "official_holdout_neighbor_overlays.png", dpi=180)
    plt.close(figure)


def _write_examples_readme(*, siac_root: Path, row_count: int) -> None:
    text = f"""# Official Sensor Mapping Example

This directory contains a fully reproducible mapping example built from:

- official Terra MODIS relative spectral response tables from NASA MCST,
- official Sentinel-2A MSI spectral response tables from ESA Copernicus,
- official Landsat 8 and Landsat 9 band JSON files from the USGS Spectral Characteristics Viewer.
- the previously composed full SIAC library at `{_relative_repo_path(siac_root)}`

Contents:

- `official_source_manifest.json`: upstream provenance for the selected band subsets
- `srfs/`: package-ready sensor JSON files for the selected bands
- `queries/`: held-out single-sample and batch query CSVs used in the docs
- `results/`: generated mapping outputs, truth tables, and pairwise error summaries

The public examples use four held-out targets from the full SIAC library:

- `blue_spruce_needles`
- `pale_brown_silty_loam`
- `tap_water`
- `asphalt_road`

Those targets are simulated to each source sensor. Single-sample examples
exclude the exact prepared `row_id`, and the batch input carries a per-sample
`exclude_row_id` column so each query removes only its own source row from the
{row_count:,}-row retrieval library.
All generated outputs use the public default `k = 10`.

Regenerate everything from the official upstream sources with:

```bash
python3 -m pip install ".[internal-build]"
python3 scripts/build_official_mapping_examples.py --siac-root {_shell_quote(_relative_repo_path(siac_root))}
```

The public write-up that explains the example commands and figures is in
[`docs/official_sensor_examples.md`](../../docs/official_sensor_examples.md).
"""
    path = EXAMPLES_ROOT / "README.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _format_reflectance(value: float) -> str:
    return f"{value:.4f}"


def _shell_block(*lines: str) -> str:
    rendered: list[str] = []
    for index, line in enumerate(lines):
        suffix = " \\" if index < len(lines) - 1 else ""
        rendered.append(f"{line}{suffix}")
    return "\n".join(rendered)


def _render_official_sensor_examples_doc(
    *,
    generated_at_utc: str,
    siac_root: Path,
    library_row_count: int,
    landcover_counts: dict[str, int],
    heldout_metadata_by_sample_id: dict[str, dict[str, str]],
    source_artifacts_by_sensor: dict[str, list[dict[str, object]]],
    truth_rows_by_sensor: dict[str, dict[str, dict[str, float]]],
) -> str:
    metrics_rows = _load_metric_rows()
    lowest = min(metrics_rows, key=lambda row: float(row["mean_abs_error"]))
    highest = max(metrics_rows, key=lambda row: float(row["mean_abs_error"]))
    primary_example = SELECTED_TARGET_SENSOR_RUNS[0]
    primary_rows = _load_result_rows(
        _single_target_output_path(
            primary_example.sample_id,
            primary_example.source_sensor,
            primary_example.target_sensor,
        )
    )
    mapped_primary = {row["band_id"]: float(row["reflectance"]) for row in primary_rows}
    truth_primary = truth_rows_by_sensor[primary_example.target_sensor][primary_example.sample_id]
    metric_band_text = ", ".join(f"`{band_id}`" for band_id in COMPARABLE_PAIRWISE_BANDS)
    full_library_root = _relative_repo_path(siac_root)
    holdout_batch_query_name = _holdout_batch_query_path().name

    prepare_runtime_block = _shell_block(
        "spectral-library prepare-mapping-library",
        f"  --siac-root {_shell_quote(full_library_root)}",
        "  --srf-root examples/official_mapping/srfs",
        "  --source-sensor modis_terra",
        "  --source-sensor sentinel2a_msi",
        "  --source-sensor landsat8_oli",
        "  --source-sensor landsat9_oli",
        "  --output-root build/official_mapping_runtime",
    )
    validate_runtime_block = _shell_block(
        "spectral-library validate-prepared-library",
        "  --prepared-root build/official_mapping_runtime",
    )

    def _target_sensor_block(example: SelectedExampleRun) -> str:
        return _shell_block(
            "spectral-library map-reflectance",
            "  --prepared-root build/official_mapping_runtime",
            f"  --source-sensor {example.source_sensor}",
            f"  --target-sensor {example.target_sensor}",
            f"  --input {_shell_quote(f'examples/official_mapping/queries/single/{example.sample_id}_{example.source_sensor}.csv')}",
            "  --output-mode target_sensor",
            f"  --exclude-row-id {_shell_quote(HELD_OUT_TARGETS_BY_ID[example.sample_id].row_id)}",
            (
                "  --output build/official_mapping_runtime/"
                f"{_single_target_output_path(example.sample_id, example.source_sensor, example.target_sensor).name}"
            ),
        )

    batch_block = _shell_block(
        "spectral-library map-reflectance-batch",
        "  --prepared-root build/official_mapping_runtime",
        f"  --source-sensor {HOLDOUT_BATCH_SOURCE_SENSOR}",
        f"  --target-sensor {HOLDOUT_BATCH_TARGET_SENSOR}",
        f"  --input {_shell_quote(f'examples/official_mapping/queries/batch/{holdout_batch_query_name}')}",
        "  --output-mode target_sensor",
        f"  --output build/official_mapping_runtime/{_holdout_batch_output_path().name}",
        f"  --diagnostics-output build/official_mapping_runtime/{_holdout_batch_diagnostics_path().name}",
    )
    full_spectrum_block = _shell_block(
        "spectral-library map-reflectance",
        "  --prepared-root build/official_mapping_runtime",
        f"  --source-sensor {FULL_SPECTRUM_SOURCE_SENSOR}",
        f"  --input {_shell_quote(f'examples/official_mapping/queries/single/{FULL_SPECTRUM_SAMPLE_ID}_{FULL_SPECTRUM_SOURCE_SENSOR}.csv')}",
        "  --output-mode full_spectrum",
        f"  --exclude-row-id {_shell_quote(HELD_OUT_TARGETS_BY_ID[FULL_SPECTRUM_SAMPLE_ID].row_id)}",
        f"  --output build/official_mapping_runtime/{_full_spectrum_output_path(FULL_SPECTRUM_SAMPLE_ID, FULL_SPECTRUM_SOURCE_SENSOR).name}",
    )

    source_table_lines = [
        "| Sensor | Official source | Repository subset |",
        "| --- | --- | --- |",
    ]
    for sensor in OFFICIAL_SENSORS:
        source_table_lines.append(
            f"| {sensor.display_name} | {sensor.source_agency} [{sensor.source_document}]({sensor.source_url}) | "
            f"[`examples/official_mapping/srfs/{sensor.filename}`](../examples/official_mapping/srfs/{sensor.filename}) |"
        )

    holdout_table_lines = [
        "| Sample id | Class | Source | Prepared row id |",
        "| --- | --- | --- | --- |",
    ]
    for target in HELD_OUT_TARGETS:
        metadata = heldout_metadata_by_sample_id[target.sample_id]
        holdout_table_lines.append(
            f"| `{target.sample_id}` | `{target.landcover_group}` | {metadata['source_name']} | `{target.row_id}` |"
        )

    primary_table_lines = [
        "| Band | Truth | Mapped |",
        "| --- | --- | --- |",
    ]
    primary_band_ids = [
        str(band["band_id"]) for band in json.loads((SRF_ROOT / f"{primary_example.target_sensor}.json").read_text())["bands"]
    ]
    for band_id in primary_band_ids:
        primary_table_lines.append(
            f"| `{band_id}` | `{_format_reflectance(truth_primary[band_id])}` | "
            f"`{_format_reflectance(mapped_primary[band_id])}` |"
        )

    artifact_summary_lines: list[str] = []
    for sensor in OFFICIAL_SENSORS:
        artifacts = source_artifacts_by_sensor[sensor.sensor_id]
        if len(artifacts) == 1:
            artifact = artifacts[0]
            artifact_summary_lines.append(
                f"- {sensor.display_name}: `{artifact['local_name']}` SHA-256 `{artifact['sha256']}`"
            )
            continue
        artifact_summary_lines.append(
            f"- {sensor.display_name}: `{len(artifacts)}` official band JSON files recorded in "
            f"[`examples/official_mapping/official_source_manifest.json`](../examples/official_mapping/official_source_manifest.json)"
        )

    landcover_lines = [
        f"- `{group}`: `{count:,}` rows"
        for group, count in landcover_counts.items()
    ]

    return f"""{GENERATED_DOC_BANNER}
# Official Sensor Examples

This page shows the bundled cross-sensor example runtime built from official
relative spectral response sources for Terra MODIS, Sentinel-2A MSI, Landsat 8
OLI, and Landsat 9 OLI.

It uses four held-out class targets drawn from the previously composed full
SIAC library: one vegetation spectrum, one soil spectrum, one water spectrum,
and one urban spectrum. Those targets are simulated to each source sensor. For
each query, the examples exclude only the matching prepared `row_id`, leaving
the rest of the external full library available.

<div class="fact-grid">
  <div><strong>4 sensors</strong><span>MODIS, Sentinel-2A, Landsat 8, Landsat 9</span></div>
  <div><strong>4 held-out targets</strong><span>vegetation, soil, water, urban</span></div>
  <div><strong>{library_row_count:,} library rows</strong><span>external full SIAC retrieval database</span></div>
  <div><strong>Example k</strong><span>public default `k = {EXAMPLE_K}`</span></div>
  <div><strong>Scored subset</strong><span>{", ".join(COMPARABLE_PAIRWISE_BANDS)}</span></div>
  <div><strong>Library root</strong><span>`{full_library_root}`</span></div>
  <div><strong>Regenerated</strong><span>{generated_at_utc[:10]} UTC</span></div>
</div>

Related pages:

- [Mathematical Foundations](theory.md)
- [Official Example Bundle](example_bundle.md)

## Official Sources

{chr(10).join(source_table_lines)}

The reduced JSON files and derived figures were regenerated from the official
upstream assets on `{generated_at_utc[:10]}` UTC. Provenance, download timestamps,
and SHA-256 hashes are stored in
[`examples/official_mapping/official_source_manifest.json`](../examples/official_mapping/official_source_manifest.json).

Recorded upstream artifacts for this commit:

{chr(10).join(artifact_summary_lines)}

## What The Example Demonstrates

- held-out reconstruction on exact full-library spectra rather than synthetic mixtures
- target-sensor mapping between MODIS, Sentinel-2A, Landsat 8, and Landsat 9
- batch mapping from one CSV input
- full-spectrum reconstruction over `400-2500 nm`
- provenance tracking for official SRF inputs

## Held-Out Target Design

{chr(10).join(holdout_table_lines)}

The retrieval library itself is not vendored under `examples/official_mapping`
because it contains `{library_row_count:,}` rows. Instead, the committed bundle
records the expected external SIAC root and the exact held-out rows in
[`examples/official_mapping/official_source_manifest.json`](../examples/official_mapping/official_source_manifest.json).

Current full-library landcover counts:

{chr(10).join(landcover_lines)}

Each example command excludes only its own query spectrum:

- single-sample runs use `--exclude-row-id <row_id>`
- the batch input file carries an `exclude_row_id` column, one exact row id per query

That keeps the other held-out targets available as neighbors while still
preventing self-matches.

All generated outputs on this page use the public default `k = {EXAMPLE_K}`.
The overlay figure below plots the top `{OVERLAY_TOP_NEIGHBORS}` neighbors from
each segment’s `k = {EXAMPLE_K}` retrieval for readability.

## Band Correspondence

| Semantic band | Terra MODIS | Sentinel-2A MSI | Landsat 8 OLI | Landsat 9 OLI |
| --- | --- | --- | --- | --- |
| `ultra_blue` | not present | `B1` | `Band 1` | `Band 1` |
| `blue` | `Band 3` | `B2` | `Band 2` | `Band 2` |
| `green` | `Band 4` | `B3` | `Band 3` | `Band 3` |
| `red` | `Band 1` | `B4` | `Band 4` | `Band 4` |
| `nir` | `Band 2` | `B8` | `Band 5` | `Band 5` |
| `swir1` | `Band 6` | `B11` | `Band 6` | `Band 6` |
| `swir2` | `Band 7` | `B12` | `Band 7` | `Band 7` |

Sentinel-2 is represented here by the `S2A` sheet from the official ESA SRF
workbook. If you need `S2B` or `S2C`, the same conversion script can be pointed
at the corresponding official sheet.

## Rebuild The Example Bundle

Regenerate the sensor JSON, example queries, results, and plot assets:

```bash
python3 -m pip install ".[internal-build]"
python3 scripts/build_official_mapping_examples.py --siac-root {_shell_quote(full_library_root)}
```

That script downloads the official source assets, writes the reduced sensor
schemas into `examples/official_mapping/srfs`, rebuilds the example queries and
outputs against the external full SIAC library, refreshes the figures in
`docs/assets`, and rewrites this page from the generated outputs. It requires
network access for the upstream SRF files and expects the full SIAC library to
already exist at `{full_library_root}` or at the path passed by `--siac-root`.

## Prepare The Runtime

Use the previously composed full SIAC library and the official-source SRF JSONs:

```bash
{prepare_runtime_block}
```

Validate the prepared runtime:

```bash
{validate_runtime_block}
```

## Visual Comparison

Selected official band responses used by the example runtime:

![Selected official band responses](assets/official_sensor_selected_bands.png)

Mean absolute target-band error across the four held-out class targets,
evaluated only on the common comparable subset
{metric_band_text}:

![Pairwise mapping error](assets/official_pairwise_band_mae.png)

Observed range in the bundled example:

- lowest comparable mean absolute band error:
  `{float(lowest["mean_abs_error"]):.4f}` for {lowest["source_label"]} -> {lowest["target_label"]}
- highest comparable mean absolute band error:
  `{float(highest["mean_abs_error"]):.4f}` for {highest["source_label"]} -> {highest["target_label"]}

The full pairwise summary, including `evaluated_band_ids` and
`evaluated_band_count`, is in
[`examples/official_mapping/results/metrics/pairwise_band_metrics.csv`](../examples/official_mapping/results/metrics/pairwise_band_metrics.csv).

Held-out Landsat 8 to Sentinel-2A batch comparison across vegetation, soil,
water, and urban targets:

![Held-out batch comparison](assets/official_holdout_batch_examples.png)

## Neighbor Overlay Diagnostic

The figure below shows the two retrievals independently for each held-out
Landsat 8 query:

- left panel: the visible-to-NIR retrieval over `400-1000 nm`
- right panel: the NIR-to-SWIR retrieval over `800-2500 nm`

Even when the input query includes all Landsat 8 reflective bands, the runtime
does **not** do one joint KNN search across the entire source vector. It always
builds two query vectors, retrieves neighbors independently for each segment,
and only then combines the reconstructed segments into the final full-spectrum
product.

Each panel overlays:

- the held-out hyperspectral query spectrum
- the segment-specific Landsat 8 query inputs used in that retrieval
- the top `{OVERLAY_TOP_NEIGHBORS}` neighbors from the segment’s `k = {EXAMPLE_K}`
  search on the full library, labeled with source-space distance

This makes one important behavior explicit: KNN is query-centric within each
segment. It ranks candidates by distance to that segment’s query features, but
it does not require the neighbors to be mutually similar or to share the same
landcover label.

![Holdout neighbor overlays](assets/official_holdout_neighbor_overlays.png)

## Single-Sample Mapping Runs

MODIS Terra to Sentinel-2A on the vegetation holdout:

```bash
{_target_sensor_block(SELECTED_TARGET_SENSOR_RUNS[0])}
```

Reference output:
[`examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[0].sample_id, SELECTED_TARGET_SENSOR_RUNS[0].source_sensor, SELECTED_TARGET_SENSOR_RUNS[0].target_sensor).name}`](../examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[0].sample_id, SELECTED_TARGET_SENSOR_RUNS[0].source_sensor, SELECTED_TARGET_SENSOR_RUNS[0].target_sensor).name})

{chr(10).join(primary_table_lines)}

The `ultra_blue` band is shown in the example table because it is a real target
output for Sentinel-2A, but it is intentionally excluded from the pairwise
heatmap so every source-target cell is scored on the same comparable six-band
subset.

Sentinel-2A to Landsat 9 on the soil holdout:

```bash
{_target_sensor_block(SELECTED_TARGET_SENSOR_RUNS[1])}
```

Reference output:
[`examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[1].sample_id, SELECTED_TARGET_SENSOR_RUNS[1].source_sensor, SELECTED_TARGET_SENSOR_RUNS[1].target_sensor).name}`](../examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[1].sample_id, SELECTED_TARGET_SENSOR_RUNS[1].source_sensor, SELECTED_TARGET_SENSOR_RUNS[1].target_sensor).name})

Landsat 8 to MODIS on the urban holdout:

```bash
{_target_sensor_block(SELECTED_TARGET_SENSOR_RUNS[2])}
```

Reference output:
[`examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[2].sample_id, SELECTED_TARGET_SENSOR_RUNS[2].source_sensor, SELECTED_TARGET_SENSOR_RUNS[2].target_sensor).name}`](../examples/official_mapping/results/selected/{_single_target_output_path(SELECTED_TARGET_SENSOR_RUNS[2].sample_id, SELECTED_TARGET_SENSOR_RUNS[2].source_sensor, SELECTED_TARGET_SENSOR_RUNS[2].target_sensor).name})

## Batch Example

The bundled batch CSV uses Landsat 8 as the source sensor for the four held-out
targets:

```bash
{batch_block}
```

The batch input file
[`examples/official_mapping/queries/batch/{holdout_batch_query_name}`](../examples/official_mapping/queries/batch/{holdout_batch_query_name})
includes an `exclude_row_id` column, so each query removes only its own exact
prepared row from the shared full-library runtime.

Reference output:
[`examples/official_mapping/results/selected/{_holdout_batch_output_path().name}`](../examples/official_mapping/results/selected/{_holdout_batch_output_path().name})

Reference diagnostics:
[`examples/official_mapping/results/selected/{_holdout_batch_diagnostics_path().name}`](../examples/official_mapping/results/selected/{_holdout_batch_diagnostics_path().name})

## Full-Spectrum Reconstruction

Reconstruct the full `400-2500 nm` spectrum from the water holdout:

```bash
{full_spectrum_block}
```

Reference output:
[`examples/official_mapping/results/selected/{_full_spectrum_output_path(FULL_SPECTRUM_SAMPLE_ID, FULL_SPECTRUM_SOURCE_SENSOR).name}`](../examples/official_mapping/results/selected/{_full_spectrum_output_path(FULL_SPECTRUM_SAMPLE_ID, FULL_SPECTRUM_SOURCE_SENSOR).name})
"""


def _write_official_sensor_examples_doc(
    *,
    generated_at_utc: str,
    siac_root: Path,
    library_row_count: int,
    landcover_counts: dict[str, int],
    heldout_metadata_by_sample_id: dict[str, dict[str, str]],
    source_artifacts_by_sensor: dict[str, list[dict[str, object]]],
    truth_rows_by_sensor: dict[str, dict[str, dict[str, float]]],
) -> None:
    OFFICIAL_SENSOR_DOC_PATH.write_text(
        _render_official_sensor_examples_doc(
            generated_at_utc=generated_at_utc,
            siac_root=siac_root,
            library_row_count=library_row_count,
            landcover_counts=landcover_counts,
            heldout_metadata_by_sample_id=heldout_metadata_by_sample_id,
            source_artifacts_by_sensor=source_artifacts_by_sensor,
            truth_rows_by_sensor=truth_rows_by_sensor,
        ),
        encoding="utf-8",
    )


def _load_metric_rows() -> list[dict[str, str]]:
    metrics_path = RESULTS_ROOT / "metrics" / "pairwise_band_metrics.csv"
    with metrics_path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _reset_generated_outputs() -> None:
    for root in (SRF_ROOT, QUERIES_ROOT, RESULTS_ROOT, EXAMPLES_ROOT / "siac"):
        if root.exists():
            shutil.rmtree(root)
        if root != EXAMPLES_ROOT / "siac":
            root.mkdir(parents=True, exist_ok=True)
    DOCS_ASSETS_ROOT.mkdir(parents=True, exist_ok=True)
    for path in DOCS_ASSETS_ROOT.glob("official_*.png"):
        path.unlink()


def build_official_mapping_examples(*, siac_root: Path | None = None) -> None:
    TMP_ROOT.mkdir(parents=True, exist_ok=True)
    _reset_generated_outputs()
    generated_at_utc = datetime.now(timezone.utc).isoformat()
    source_artifacts_by_sensor: dict[str, list[dict[str, object]]] = {}
    resolved_siac_root = _resolve_full_library_root(siac_root)
    library_row_count, landcover_counts, heldout_metadata_by_sample_id = _inspect_full_library(resolved_siac_root)
    build_summary_path = resolved_siac_root / "build_summary.json"
    build_summary_payload = json.loads(build_summary_path.read_text(encoding="utf-8")) if build_summary_path.exists() else None
    build_summary = (
        {
            key: value
            for key, value in build_summary_payload.items()
            if key in {"total_spectra", "classified_spectra", "landcover_counts", "excluded_source_ids"}
        }
        if build_summary_payload is not None
        else None
    )

    with tempfile.TemporaryDirectory(prefix="official_sensor_sources_", dir=str(REPO_ROOT / "tmp")) as tmpdir:
        tmp_root = Path(tmpdir)
        modis_artifact = _download(SENSOR_BY_ID["modis_terra"].source_url, tmp_root / "Terra_RSR_in-band.xlsx")
        sentinel_artifact = _download(
            SENSOR_BY_ID["sentinel2a_msi"].source_url,
            tmp_root / "Sentinel-2_Spectral_Response_Functions_2024_4.0.xlsx",
        )
        modis_path = tmp_root / "Terra_RSR_in-band.xlsx"
        sentinel_path = tmp_root / "Sentinel-2_Spectral_Response_Functions_2024_4.0.xlsx"

        sensor_payloads = {
            "modis_terra": _parse_modis_sensor(SENSOR_BY_ID["modis_terra"], modis_path),
            "sentinel2a_msi": _parse_sentinel_sensor(SENSOR_BY_ID["sentinel2a_msi"], sentinel_path),
        }
        landsat8_payload, landsat8_artifacts = _parse_landsat_sensor(SENSOR_BY_ID["landsat8_oli"])
        landsat9_payload, landsat9_artifacts = _parse_landsat_sensor(SENSOR_BY_ID["landsat9_oli"])
        sensor_payloads["landsat8_oli"] = landsat8_payload
        sensor_payloads["landsat9_oli"] = landsat9_payload
        source_artifacts_by_sensor["modis_terra"] = [modis_artifact.to_dict()]
        source_artifacts_by_sensor["sentinel2a_msi"] = [sentinel_artifact.to_dict()]
        source_artifacts_by_sensor["landsat8_oli"] = landsat8_artifacts
        source_artifacts_by_sensor["landsat9_oli"] = landsat9_artifacts

    for sensor in OFFICIAL_SENSORS:
        _json_write(SRF_ROOT / sensor.filename, sensor_payloads[sensor.sensor_id])

    truth_spectra = _load_selected_spectra(
        resolved_siac_root,
        {
            target.sample_id: (target.source_id, target.spectrum_id, target.sample_name)
            for target in HELD_OUT_TARGETS
        },
    )

    provenance_payload = {
        "generated_at_utc": generated_at_utc,
        "description": "Official-source band subsets used for the documentation and mapping examples.",
        "comparison_band_ids": list(COMPARABLE_PAIRWISE_BANDS),
        "example_design": {
            "strategy": "held_out_exact_rows_from_external_full_siac_library",
            "description": (
                "Four exact spectra are selected from the previously composed full SIAC library as public targets. "
                "Each query excludes only its own prepared row_id at mapping time, leaving the rest of the full library available."
            ),
            "held_out_samples": [
                {
                    "sample_id": target.sample_id,
                    "row_id": target.row_id,
                    "source_id": target.source_id,
                    "spectrum_id": target.spectrum_id,
                    "sample_name": target.sample_name,
                    "source_name": heldout_metadata_by_sample_id[target.sample_id]["source_name"],
                    "landcover_group": target.landcover_group,
                    "title": target.title,
                    "description": target.description,
                }
                for target in HELD_OUT_TARGETS
            ],
            "library_reference": {
                "mode": "external_full_siac_library",
                "siac_root": _relative_repo_path(resolved_siac_root),
                "metadata_csv": _relative_repo_path(resolved_siac_root / "tabular" / "siac_spectra_metadata.csv"),
                "spectra_csv": _relative_repo_path(resolved_siac_root / "tabular" / "siac_normalized_spectra.csv"),
                "row_count": library_row_count,
                "landcover_counts": landcover_counts,
                "build_summary_path": _relative_repo_path(build_summary_path) if build_summary_path.exists() else None,
                "build_summary": build_summary,
            },
            "self_exclusion_policy": "exclude_matching_row_id_only",
            "example_k": EXAMPLE_K,
        },
        "sensors": [
            {
                "sensor_id": sensor.sensor_id,
                "display_name": sensor.display_name,
                "source_agency": sensor.source_agency,
                "source_document": sensor.source_document,
                "source_url": sensor.source_url,
                "source_note": sensor.source_note,
                "source_artifacts": source_artifacts_by_sensor[sensor.sensor_id],
                "selected_bands": [
                    {
                        "band_id": band.band_id,
                        "official_band": band.official_band,
                        "segment": band.segment,
                        "description": band.description,
                    }
                    for band in sensor.bands
                ],
            }
            for sensor in OFFICIAL_SENSORS
        ],
    }
    _json_write(EXAMPLES_ROOT / "official_source_manifest.json", provenance_payload)

    truth_rows_by_sensor = _collect_reflectance_rows(truth_spectra, sensor_payloads)
    for sensor_id, sample_rows in truth_rows_by_sensor.items():
        for sample_id, reflectance in sample_rows.items():
            _write_single_query(_single_query_path(sample_id, sensor_id), reflectance)

    source_band_ids = tuple(
        str(band["band_id"]) for band in sensor_payloads[HOLDOUT_BATCH_SOURCE_SENSOR]["bands"]  # type: ignore[index]
    )
    _write_batch_query(
        _holdout_batch_query_path(),
        truth_rows_by_sensor[HOLDOUT_BATCH_SOURCE_SENSOR],
        source_band_ids,
        exclude_row_ids={target.sample_id: target.row_id for target in HELD_OUT_TARGETS},
    )
    _write_truth_tables(truth_spectra, sensor_payloads)
    with tempfile.TemporaryDirectory(prefix="official_mapping_runtime_", dir=str(TMP_ROOT)) as tmpdir:
        prepared_root = Path(tmpdir) / "prepared"
        _prepare_example_runtime(prepared_root, resolved_siac_root)
        _write_selected_cli_outputs(prepared_root)
        metrics = _write_pairwise_metrics(prepared_root, truth_rows_by_sensor)
    diagnostics_payload = _load_batch_diagnostics_payload()
    neighbor_spectra = _load_neighbor_spectra(resolved_siac_root, _top_neighbor_row_ids(diagnostics_payload))
    _plot_selected_bands(sensor_payloads)
    _plot_pairwise_heatmap(metrics)
    _plot_holdout_batch_examples(sensor_payloads, truth_rows_by_sensor)
    _plot_holdout_neighbor_overlays(truth_spectra, neighbor_spectra, sensor_payloads, truth_rows_by_sensor)
    _write_examples_readme(siac_root=resolved_siac_root, row_count=library_row_count)
    _write_official_sensor_examples_doc(
        generated_at_utc=generated_at_utc,
        siac_root=resolved_siac_root,
        library_row_count=library_row_count,
        landcover_counts=landcover_counts,
        heldout_metadata_by_sample_id=heldout_metadata_by_sample_id,
        source_artifacts_by_sensor=source_artifacts_by_sensor,
        truth_rows_by_sensor=truth_rows_by_sensor,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Regenerate the official MODIS, Sentinel-2A, and Landsat mapping example bundle.",
    )
    parser.add_argument(
        "--siac-root",
        default="",
        help=(
            "Path to the previously composed full SIAC library root. "
            f"Defaults to {FULL_LIBRARY_ENV_VAR}, then {DEFAULT_FULL_LIBRARY_ROOT.relative_to(REPO_ROOT)} if present."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    build_official_mapping_examples(siac_root=Path(args.siac_root) if args.siac_root else None)
    print(json.dumps({"status": "ok", "examples_root": str(EXAMPLES_ROOT)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
